# Generated by Django 3.2.16 on 2022-11-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='Task_Id',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
