# Generated by Django 3.2.16 on 2022-11-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_app', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='regions',
            field=models.ManyToManyField(blank=True, to='query_app.Regions'),
        ),
    ]
